-- OBSOLETO — não executar.
-- Recriava políticas abertas em trabalhos/relatórios e desfazia a migração 036.
-- Fonte de verdade: pwa/supabase-permissoes.sql (SQL Editor, colar tudo → Run)
-- ou pwa/supabase/migrations/040_permissoes_completas.sql
